image: docker:stable

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - Build primary resources
  - Test
  - Build

build:resources:
  stage: Build primary resources
  only:
    refs:
      - main
    changes:
      - ".gitlab-ci.yml"
      - "Dockerfile"
      - "composer.json"
      - "composer.lock"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker info
    - docker pull $CI_REGISTRY_IMAGE:php-${CI_COMMIT_REF_SLUG} || true
    - docker build --build-arg SSH_PRIVATE_KEY --cache-from ${CI_REGISTRY_IMAGE}:php-${CI_COMMIT_REF_SLUG} --tag ${CI_REGISTRY_IMAGE}:php-${CI_COMMIT_REF_SLUG} -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:php-${CI_COMMIT_REF_SLUG}

test:
  stage: Test
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker info
    - docker pull $CI_REGISTRY_IMAGE:php-${CI_COMMIT_REF_SLUG} || true
    - docker run --rm -w /app -v "$(pwd):/app" $CI_REGISTRY_IMAGE:php-${CI_COMMIT_REF_SLUG} composer install --dev
    - docker run --rm -w /app -v "$(pwd):/app" $CI_REGISTRY_IMAGE:php-${CI_COMMIT_REF_SLUG} php bin/phpunit
