image: docker:stable

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - Build primary resources
  - Test
  - Build

build:resources:
  stage: Build primary resources
  only:
    refs:
      - main
    changes:
      - ".gitlab-ci.yml"
      - "Dockerfile"
      - "composer.json"
      - "composer.lock"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker info
    - docker pull $CI_REGISTRY_IMAGE:php-main || true
    - docker build --build-arg SSH_PRIVATE_KEY --cache-from ${CI_REGISTRY_IMAGE}:php-main --tag ${CI_REGISTRY_IMAGE}:php-main -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:php-main

#test:
#  stage: Test
#  before_script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#  script:
#    - docker info
#    - docker pull $CI_REGISTRY_IMAGE:php-${CI_COMMIT_REF_SLUG} || true
#    - docker run --rm -w /app -v "$(pwd):/app" $CI_REGISTRY_IMAGE:php-main composer install
#    - docker run --rm -w /app -v "$(pwd):/app" $CI_REGISTRY_IMAGE:php-main php bin/phpunit

build:app:
  stage: Build
  only:
    - tags
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:app-latest || true
    - docker build --cache-from ${CI_REGISTRY_IMAGE}:app-latest --tag ${CI_REGISTRY_IMAGE}:app-${CI_COMMIT_TAG} --tag ${CI_REGISTRY_IMAGE}:app-latest -f Dockerfile.deploy .
    - docker push $CI_REGISTRY_IMAGE:app-${CI_COMMIT_TAG}
    - docker push $CI_REGISTRY_IMAGE:app-latest
