version: '3'

services:
  phpmyadmin:
    networks:
      - default
      - traefik
    depends_on:
      - database
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root_password
    labels:
      - traefik.enable=true
      - traefik.http.routers.dc_symfony_phpmyadmin.tls=true
      - traefik.http.services.dc_symfony_phpmyadmin.loadbalancer.server.port=80
      - traefik.http.routers.dc_symfony_phpmyadmin.tls.certResolver=patiashvili
      - traefik.http.routers.dc_symfony_phpmyadmin.rule=Host(`phpmyadmin.dc.patiashvili`)

  database:
    image: mariadb:latest
    networks:
      - default
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony_password
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=symfony

  php:
    networks:
      - default
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: php
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.gitconfig:/root/.gitconfig:ro

  phpunit:
    networks:
      - default
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: /app/vendor/bin/phpunit
    working_dir: /app
    volumes:
      - ./:/app

  symfony:
    networks:
      - default
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: symfony
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.gitconfig:/root/.gitconfig:ro

  web:
    networks:
      - default
      - traefik
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    entrypoint:
     - symfony
     - server:start
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.gitconfig:/root/.gitconfig:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.dc_symfony.tls=true
      - traefik.http.services.dc_symfony.loadbalancer.server.port=8000
      - traefik.http.routers.dc_symfony.tls.certResolver=patiashvili
      - traefik.http.routers.dc_symfony.rule=Host(`www.dc.patiashvili`)

  composer:
    networks:
      - default
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: composer
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.gitconfig:/root/.gitconfig:ro

  instance:
    image: test
    networks:
      - default
      - traefik
    depends_on:
      - database
    ports:
      - "8000:80"
    env_file:
      - .env.local
    labels:
      - traefik.enable=true
      - traefik.http.routers.dc_symfony.tls=true
      - traefik.http.services.dc_symfony.loadbalancer.server.port=8000
      - traefik.http.routers.dc_symfony.tls.certResolver=patiashvili
      - traefik.http.routers.dc_symfony.rule=Host(`www.dc.patiashvili`)

volumes:
  mariadb-data:

networks:
  default:
    driver: bridge
  traefik:
    name: traefik_proxy